# Site settings
name: Sanjana Mehta
title: Sanjana Mehta | Product Manager
description: I make money and feel fulfilled by envisioning experiences that delight users
url: https://sanjusan.github.io
baseurl: '/Website3.0/'
email: sanjsmehta@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:sanjsmehta@gmail.com
  - title: twitter
    url: https://twitter.com/mehta_sanjana
  - title: instagram
    url: https://instagram.com/sanjs_mehta
  - title: github
    url: https://github.com/sanjusan
  - title: linkedin
    url: https://www.linkedin.com/in/sanjanamehta/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
